//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreadInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bread
    {
        public int Id { get; set; }
        public string bread_name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
